### ISSUE TITLE
Select component returns object when it shouldn't

### ISSUE THREAD

**Issue by tomwerkheiser** [crompco/kickstart#11]
The select component returns an object if the initial value is 0. But if you try to use '0' the select doesn't show the placeholder.

**Comment by gdecris** [comment]
I don't think we should assume 0 is the placeholder. You could have a legit value of 0

**Comment by gdecris** [comment]
New behavior is to assume an object only when the value is an object or the value is null. So when using this with v-model just initialize to an empty string

**Comment by gdecris** [comment]
new prop added `force-values` when set to true it will use the key value from the option 
in version 0.4.0 328e78ed06e8ad98e3238d8a30a9ce20c3eb292c
